### ISSUE TITLE
pyhipster results "node command not found" on windows

### ISSUE THREAD

**Issue by eitanarat** [pyhipster/generator-pyhipster#14]
Hi champ,
I tried to run the generator after updating all the tools as required in the instructions.
But I'm getting this error:

$ pyhipster
C:\Users\eitan\AppData\Roaming\npm/node_modules/node/bin/node: line 1: This: command not found

This folder does exist yet it is not running.
btw, I would prefer to use the node in the PATH
I'm using Windows 11 OS

Thanks Eitan

**Comment by sudeephazra** [comment]
Looking into it. Regret the delay in responding.

**Comment by sudeephazra** [comment]
@eitanarat  Please run the command ``node --version`` from ``C:\Users\eitan\AppData\Roaming\npm/node_modules/node/bin`` and also from ``C:\`` and share the output.

**Comment by sudeephazra** [comment]
Please also check if the full logs can be shared. It should be displayed as ``npm ERR! A complete log of this run can be found in: <C:\Users\eitan\AppData\Roaming\XXyyZZ>``

**Comment by sudeephazra** [comment]
Please try with the latest release of the generator.
