### ISSUE TITLE
poetry: not found when running pyhipster in docker

### ISSUE THREAD

**Issue by mapto** [pyhipster/generator-pyhipster#22]
How to reproduce:
1. I start the container
2. run `pyhipster` without arguments in it
3. Choose default configuration

Instead of installing backend, output contains:
>...
>    create README.md
>    force .yo-rc.json
>Git repository initialized.
>     info Installing Python modules
>/bin/sh: 1: poetry: not found
>
>Changes to package.json were detected.
>
>Running npm install for you to install the required dependencies.
>...

The problem is that poetry is installed in `/root/.local/bin`, but the `pyhipster` user does not have access to the binary. It also needs to be added to `$PATH`.

I've tried solving the problem in a pull request, but I get problems with node that I am not comfortable resolving myself. In case anyone else wants to give it a try, my suggested changes in `Dockerfile` are adding [after line 55](https://github.com/pyhipster/generator-pyhipster/blob/main/Dockerfile#L55C58-L55C63):
>  chmod a+x /root/.local/bin/poetry  && \

and [change line 66](https://github.com/pyhipster/generator-pyhipster/blob/main/Dockerfile#L66) to:
> ENV PATH $PATH:/usr/bin:/root/.local/bin

**Comment by mapto** [comment]
A current workaround is to run these two lines after you [enter the container](https://pyhipster.github.io/generator-pyhipster/docs/getting-started.html#docker), but before starting with [calls to pyhipster](https://pyhipster.github.io/generator-pyhipster/docs/getting-started.html#creating-your-first-pyhipster-full-stack-application):

>curl -sSL https://install.python-poetry.org | python3 -
>export PATH=$PATH:/home/pyhipster/.local/bin

**Comment by sudeephazra** [comment]
Thanks for highlighting this. It has already been observed and being actioned upon. This will be fixed in the next release.

**Comment by sudeephazra** [comment]
Fixed in c53aa02547b005fcdf0b084848a7d36b8a62f3aa
